<a href="https://colab.research.google.com/github/tavish-1721/Tavish-/blob/main/PyTorch_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # should print True
print(torch.cuda.get_device_name(0))  # should show Tesla T4

2.10.0+cpu
False


AssertionError: Torch not compiled with CUDA enabled

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # should now be True

2.10.0+cu128
True


In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())  # should print True
print(torch.cuda.get_device_name(0))  # should show Tesla T4

2.10.0+cu128
True
Tesla T4


In [ ]:
import torch
x=torch.tensor([1,2,3,4,5])  #1D-TENSOR
print(x)


tensor([1, 2, 3, 4, 5])


In [ ]:
y=torch.tensor( #2d tensor
    [[1,2],
     [3,4]]
)
print(y)

tensor([[1, 2],
        [3, 4]])


In [ ]:
torch.zeros(3,2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
torch.rand(2,2)

tensor([[0.2222, 0.9228],
        [0.9577, 0.5321]])

In [ ]:
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)

torch.Size([3, 3])


In [ ]:
#indexing
i=torch.tensor([10,20,30])
print(i[1])

d=torch.tensor([[10,20,30],[40,50,60]])
print(d[1,2])

tensor(20)
tensor(60)


In [ ]:
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[-6, -6, -6],
        [-6, -6, -6]])
tensor([[ 7, 16, 27],
        [40, 55, 72]])
tensor([[0.1429, 0.2500, 0.3333],
        [0.4000, 0.4545, 0.5000]])


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=torch.from_numpy(a) #making tensors from numpy
#both will be using sam memory location



In [ ]:
import torch
#input data
x=torch.tensor([1.,2.,3.,4.])
y=torch.tensor([2.,4.,6.,8.])
#now for m and c in st. line
m=torch.tensor(0.0)
c=torch.tensor(0.0)

#y=mx+c
y_pred=m*x+c
#loss
loss=((y_pred-y)**2).mean() #mean squared error,y_pred-model prediction,y-true value

print("predicted values",y_pred)
print("actual values",y)
print("loss",loss)


predicted values tensor([0., 0., 0., 0.])
actual values tensor([2., 4., 6., 8.])
loss tensor(30.)


In [ ]:
import torch
#requires_grad=True tells the no pytorch we have to track for making changes and getting better results.
#torch.tensor(value,requires_grad=True)
w=torch.tensor(2.0,requires_grad=True)
x=torch.tensor(3.0)
y=w*x
print(y)


tensor(6., grad_fn=<MulBackward0>)


In [ ]:
import torch
x=torch.tensor(2.0)
w=torch.tensor(3.0,requires_grad=True)
y_pred=w*x
y_true=torch.tensor(10.0)
loss=(y_pred-y_true)**2
print(loss)
loss.backward() #helps in telling the mistake in w (mean squared error),without this we do not have any gradient to update anything
print("prediction",y_pred.item())
print("loss",loss.item())
print("w.grad",w.grad.item())






tensor(16., grad_fn=<PowBackward0>)
prediction 6.0
loss 16.0


AttributeError: 'NoneType' object has no attribute 'item'

In [ ]:
import torch

x = torch.tensor(2.0)
w = torch.tensor(3.0, requires_grad=True)
y_true = torch.tensor(10.0)
lr = 0.1

# --- before update ---
y_pred = w * x
loss = (y_pred - y_true) ** 2
loss.backward()

print("Before update")
print("w:       ", w.item())          # 3.0
print("loss:    ", loss.item())       # 16.0
print("gradient:", w.grad.item())     # -16.0
"""loss = (w*x - y_true)²
     = (w·2 - 10)²
∂loss/∂w = 2 · (w·x - y_true) · x
          = 2 · (3·2 - 10)   · 2
          = 2 · (6 - 10)     · 2
          = 2 · (−4)         · 2
          = −16"""

# --- update ---
with torch.no_grad(): #no graph recorded,stops pytorch gradient tracking,w updated safely,without this:w update would break the graph
    w -= lr * w.grad
w.grad.zero_() #making the gradient zero otherwise gradients add into the first

# --- recompute after update ---
y_pred = w * x
loss = (y_pred - y_true) ** 2

print("\nAfter update")
print("w:       ", w.item())          # 4.6
print("loss:    ", loss.item())       # 0.64  ← now correct
print("gradient:", w.grad)            # None (zeroed in w.gead_zero, no new backward yet)

Before update
w:        3.0
loss:     16.0
gradient: -16.0

After update
w:        4.599999904632568
loss:     0.6400002837181091
gradient: tensor(0.)


In [ ]:
import torch
x= torch.tensor([1.,2.,3.,4.])
y_true=torch.tensor([2.,4.,6.,8.]) #correct values
w=torch.tensor(0.0,requires_grad=True)

lr=0.1
epochs=10 #no. of times AI have to learn

for epoch in range(epochs):
    #step 1 prediction
    y_pred=w*x
    #step  2 loss
    loss=((y_pred-y_true)**2).mean()
    loss.backward()

    with torch.no_grad():
        w-=lr*w.grad

    print(f"Epoch{epoch+1}:w={w.item():.4f},loss={loss.item():.4f}")

Epoch1:w=3.0000,loss=30.0000
Epoch2:w=4.5000,loss=7.5000
Epoch3:w=2.2500,loss=46.8750
Epoch4:w=-0.3750,loss=0.4688
Epoch5:w=0.5625,loss=42.3047
Epoch6:w=3.6562,loss=15.4980
Epoch7:w=4.2656,loss=20.5737
Epoch8:w=1.4766,loss=38.4979
Epoch9:w=-0.5273,loss=2.0549
Epoch10:w=1.2598,loss=47.9060


In [ ]:
#Neural Network,class
import torch
import torch.nn as nn

"""classMyModel(nn.Module):
def __init_(self):
super()._init_()"""
class MyModel(nn.Module): #neural network class is created, and this class is following PyTorch rules-numbers should be trained,learning allowed,data set can be loaded and saved and model can be optimized
  def __init__(self):   #what should be already there in model initially when created-learning no. ,layers,internal parts
    super()._init__() # without this nothing can be inherited from nn.module and model will break

    self.w=nn.Parameter(torch.tensor(0.0)) #self.w=nn.Parameter(torch.tensor(0.0)) replaces w=troch.tensor(0.0,requires_grad=True) automatically,nn.parameter tells PyTorch to track its gardient automatically.
    def forward(self,x): #defines the forward pass-what the model does with input(x),when we will call model(x),it will do w*x
     return self.w*x

In [ ]:
import torch
import torch.nn as nn

"""nn.linear(input_features,output_features)
nn.linear(3,1)
eg -input are height ,wight and risk convert it into risk score,3 input into 1 output"""

layer=nn.Linear(3,2)
x=torch.tensor([[1.0,2.0,3.0]]) #shape[1,3] -input
y=layer(x)
print(y)

#three no in input,two in output as expected ,so pytorch has automatically created weight,bias and then appliead the calculation,layers are also stacked(many layers not only one as 3 are input) so input is gone and output is produced,in every step data is channging itself a little bit and understanding is increasing(bias)


tensor([[0.5343, 0.8067]], grad_fn=<AddmmBackward0>)


In [ ]:
#Activation Functions,no activation means no intelligence
#There may be 5 layers but it will behave like a single layer ,model will become useless for a complex model because output=input*weight+bias is a linear formula
#model will not be able to learn curves,how to find shapes and also not be able to learn from data
#activation function is like a decison maker that decides which information shpould be passed forward and which info should be blocked.
#Linear-activation-linear-activation-output
#nn.Relu(Hidden Layer)-Rectified linear unit,-ve data becomes 0 and positive will be positive
#nn.Sigmoid(Binary Output) -used only in final output,Yes/No,0/1
#nn.Softmax(Multiclass output)-takes many numbers and convert them into one single number,or one single strongest other becomes week like [2,1,0]-[0.7,0.2,0.1],now 0.7 is the strongest
#input-linear-Relu-linear-Softmax/Sigmoid-output


In [ ]:
#optimiser is like a helper that automatically update all learning numbers(w1,w2,w3,..) using gradient like we do not have to use now w-=lr*w.grad
#all training steps will be there in gradient,decides how much to change each number by,clears the old gradient

#Optimisers type
#SGD-simple,perfect for basic learning,move towards its target slowly,lr=0.01
#torch.optim.SGD(model.parameter(),lr=0.01)
#Adam-auto adapt speed,perfect for faster learning,noisy data can be handled easily
#torch.optim.Adam(model.parameter(),lr=0.001)

#Step
#optimiser.zero_grad()-forward pass-loss caln -loss backward()-optimiser.step

import torch
import torch.nn as nn
import torch.optim as optim

class myModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.Linear=nn.Linear(1,1)
  def forward(self,x):
    return self.Linear(x)

x=torch.tensor([[1.],[2.],[3.],[4.]]) #samples-[1,4]
y=torch.tensor([[2.],[4.],[6.],[8.]]) #shape-[1,4]

model= myModel() #creates the model,initialises random weight
loss_fn=nn.MSELoss() #Mean squared error-measures how wrong predictions are

optimiser =optim.Adam(model.parameters(),lr=0.1) #adam(optimiser) will update all weights,parameters means using all learning numbers
for epoch in range(10): #loss get smaller with every next iteration
  optimiser.zero_grad() #clears gradients from previous epoch and avoids accumulation
  y_pred=model(x)
  loss=loss_fn(y_pred,y)#loss=mean((y_predict-y_true)^2)
  loss.backward() #computes gradient, backward pass-computes gradient of loss with respect to every learnable parameter(weight and bias),del loss/del weight,del loss/del bias,so loss is loss wrt weight +loss wrt to bias
  optimiser.step() #weights updated,adam uses the gradient to update weight and bias

  print(f"Epoch{epoch+1},Loss={loss.item():.4f}")
#after 10 epochs model.linear.weight will be close to 2.0 and module.linear.bias woill be close to 0.0,bcoz the relation is y=2x+0

torch.save(model.state_dict(),"linear_model.pth")

Epoch1,Loss=34.5911
Epoch2,Loss=30.4590
Epoch3,Loss=26.6052
Epoch4,Loss=23.0339
Epoch5,Loss=19.7480
Epoch6,Loss=16.7489
Epoch7,Loss=14.0366
Epoch8,Loss=11.6090
Epoch9,Loss=9.4622
Epoch10,Loss=7.5898


In [ ]:
import os
print(os.path.exists("linear_model.pth"))  # True = saved successfully
print(os.getcwd())                          # shows which folder it saved to

True
/content
